# Generated by Django 5.0.6 on 2024-05-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('hunger_level', models.IntegerField(default=0)),
                ('happiness_level', models.IntegerField(default=0)),
            ],
        ),
    ]
