# Generated by Django 5.0.6 on 2024-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompet',
            name='bathroom_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custompet',
            name='friendliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custompet',
            name='health_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custompet',
            name='status',
            field=models.CharField(choices=[('DEAD', 'Dead'), ('ALIVE', 'Alive')], default='ALIVE', max_length=5),
        ),
    ]
